spring:
  application:
    name: mqt
  rabbitmq:
    username: user
    password: 123456
    virtual-host: /mqt
    host: 192.168.0.100
    port: 5672
    #   每次只发一条消息
    listener:
      simple:
        prefetch: 1
        # 设置消费端手动 ack
        acknowledge-mode: manual
        # 是否支持重试
        retry:
          enabled: true
